---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes

- name: "install node and npm"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: true
    production: true
    state: present
- name: "Create a directory"
  file:
    path: ~/web
    state: directory

- name: "Copy index file"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"
- name: "Execute node"
  shell: |
    pm2 start ~/web/index.js -f